package br.com.louvor4.api.enums;

public enum NotificationType {
    EVENT_INVITE,
    EVENT_PARTICIPANT_ACCEPTED,
    EVENT_PARTICIPANT_DECLINED,
    EVENT_PARTICIPANT_REMOVED,
    EVENT_UPDATED,
    EVENT_CANCELLED,
    EVENT_REMINDER,

    EVENT_SONG_ADDED,
    EVENT_SONG_REMOVED,
    EVENT_SCHEDULE_UPDATED,

    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_REMOVED,

    MESSAGE_RECEIVED,

    SYSTEM_NOTIFICATION
}
